FROM apache/airflow:2.9.3-python3.10

# -----------------------------
# Install Docker CLI as root
# -----------------------------
USER root

# Install Docker CLI (new) + dependencies
RUN apt-get update && apt-get install -y \
    ca-certificates curl gnupg lsb-release \
    && install -m 0755 -d /etc/apt/keyrings \
    && curl -fsSL https://download.docker.com/linux/debian/gpg \
    | gpg --dearmor -o /etc/apt/keyrings/docker.gpg \
    && chmod a+r /etc/apt/keyrings/docker.gpg \
    && echo \
    "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \
    https://download.docker.com/linux/debian \
    $(. /etc/os-release && echo "$VERSION_CODENAME") stable" \
    > /etc/apt/sources.list.d/docker.list \
    && apt-get update \
    && apt-get install -y docker-ce-cli \
    && rm -rf /var/lib/apt/lists/*

# -----------------------------
# Switch to airflow user for pip
# -----------------------------
USER airflow

RUN pip install --no-cache-dir pymongo==4.6.3
